### ISSUE TITLE
Code Indentation: Ruby standards

### ISSUE THREAD

**Issue by ephemeral972** [BlueJeansNetwork/goblin#4]
Hey,

This is Sai, wanted to say Good initiative on open sourcing it.  I also did notice that most of the code is not indented as per good ruby coding standards, example here
https://github.com/BlueJeansNetwork/goblin/blob/master/src/runner/collector.rb
No 2 space indenting between def and existing classes. 

See the ruby standards here
https://github.com/dmitrinesterenko/ruby-style-guide

**Comment by shegde** [comment]
Thanks Sai. Fixed in 84af7df1ea208037b43dc2c832c9da77b117cb9f.
